-- Seed data: ISO 3166-1 countries (German display names + Alpha-2 codes)
-- Used as selectable values for the optional "origin country" purchase attribute.

INSERT INTO countries (name, iso_code) VALUES
('Afghanistan', 'AF'),
('Ägypten', 'EG'),
('Albanien', 'AL'),
('Algerien', 'DZ'),
('Andorra', 'AD'),
('Angola', 'AO'),
('Antigua und Barbuda', 'AG'),
('Äquatorialguinea', 'GQ'),
('Argentinien', 'AR'),
('Armenien', 'AM'),
('Aserbaidschan', 'AZ'),
('Äthiopien', 'ET'),
('Australien', 'AU'),
('Bahamas', 'BS'),
('Bahrain', 'BH'),
('Bangladesch', 'BD'),
('Barbados', 'BB'),
('Belgien', 'BE'),
('Belize', 'BZ'),
('Benin', 'BJ'),
('Bhutan', 'BT'),
('Bolivien', 'BO'),
('Bosnien und Herzegowina', 'BA'),
('Botsuana', 'BW'),
('Brasilien', 'BR'),
('Brunei', 'BN'),
('Bulgarien', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Chile', 'CL'),
('China', 'CN'),
('Costa Rica', 'CR'),
('Dänemark', 'DK'),
('Deutschland', 'DE'),
('Dominica', 'DM'),
('Dominikanische Republik', 'DO'),
('Dschibuti', 'DJ'),
('Ecuador', 'EC'),
('El Salvador', 'SV'),
('Elfenbeinküste', 'CI'),
('Eritrea', 'ER'),
('Estland', 'EE'),
('Eswatini', 'SZ'),
('Fidschi', 'FJ'),
('Finnland', 'FI'),
('Frankreich', 'FR'),
('Gabun', 'GA'),
('Gambia', 'GM'),
('Georgien', 'GE'),
('Ghana', 'GH'),
('Grenada', 'GD'),
('Griechenland', 'GR'),
('Guatemala', 'GT'),
('Guinea', 'GN'),
('Guinea-Bissau', 'GW'),
('Guyana', 'GY'),
('Haiti', 'HT'),
('Honduras', 'HN'),
('Indien', 'IN'),
('Indonesien', 'ID'),
('Irak', 'IQ'),
('Iran', 'IR'),
('Irland', 'IE'),
('Island', 'IS'),
('Israel', 'IL'),
('Italien', 'IT'),
('Jamaika', 'JM'),
('Japan', 'JP'),
('Jemen', 'YE'),
('Jordanien', 'JO'),
('Kambodscha', 'KH'),
('Kamerun', 'CM'),
('Kanada', 'CA'),
('Kap Verde', 'CV'),
('Kasachstan', 'KZ'),
('Katar', 'QA'),
('Kenia', 'KE'),
('Kirgisistan', 'KG'),
('Kiribati', 'KI'),
('Kolumbien', 'CO'),
('Komoren', 'KM'),
('Kongo, Demokratische Republik', 'CD'),
('Kongo, Republik', 'CG'),
('Kroatien', 'HR'),
('Kuba', 'CU'),
('Kuwait', 'KW'),
('Laos', 'LA'),
('Lesotho', 'LS'),
('Lettland', 'LV'),
('Libanon', 'LB'),
('Liberia', 'LR'),
('Libyen', 'LY'),
('Liechtenstein', 'LI'),
('Litauen', 'LT'),
('Luxemburg', 'LU'),
('Madagaskar', 'MG'),
('Malawi', 'MW'),
('Malaysia', 'MY'),
('Malediven', 'MV'),
('Mali', 'ML'),
('Malta', 'MT'),
('Marokko', 'MA'),
('Marshallinseln', 'MH'),
('Mauretanien', 'MR'),
('Mauritius', 'MU'),
('Mexiko', 'MX'),
('Mikronesien', 'FM'),
('Moldau', 'MD'),
('Monaco', 'MC'),
('Mongolei', 'MN'),
('Montenegro', 'ME'),
('Mosambik', 'MZ'),
('Myanmar', 'MM'),
('Namibia', 'NA'),
('Nauru', 'NR'),
('Nepal', 'NP'),
('Neuseeland', 'NZ'),
('Nicaragua', 'NI'),
('Niederlande', 'NL'),
('Niger', 'NE'),
('Nigeria', 'NG'),
('Nordkorea', 'KP'),
('Nordmazedonien', 'MK'),
('Norwegen', 'NO'),
('Oman', 'OM'),
('Österreich', 'AT'),
('Osttimor', 'TL'),
('Pakistan', 'PK'),
('Palau', 'PW'),
('Panama', 'PA'),
('Papua-Neuguinea', 'PG'),
('Paraguay', 'PY'),
('Peru', 'PE'),
('Philippinen', 'PH'),
('Polen', 'PL'),
('Portugal', 'PT'),
('Ruanda', 'RW'),
('Rumänien', 'RO'),
('Russland', 'RU'),
('Salomonen', 'SB'),
('Sambia', 'ZM'),
('Samoa', 'WS'),
('San Marino', 'SM'),
('São Tomé und Príncipe', 'ST'),
('Saudi-Arabien', 'SA'),
('Schweden', 'SE'),
('Schweiz', 'CH'),
('Senegal', 'SN'),
('Serbien', 'RS'),
('Seychellen', 'SC'),
('Sierra Leone', 'SL'),
('Simbabwe', 'ZW'),
('Singapur', 'SG'),
('Slowakei', 'SK'),
('Slowenien', 'SI'),
('Somalia', 'SO'),
('Spanien', 'ES'),
('Sri Lanka', 'LK'),
('St. Kitts und Nevis', 'KN'),
('St. Lucia', 'LC'),
('St. Vincent und die Grenadinen', 'VC'),
('Südafrika', 'ZA'),
('Sudan', 'SD'),
('Südkorea', 'KR'),
('Südsudan', 'SS'),
('Suriname', 'SR'),
('Syrien', 'SY'),
('Tadschikistan', 'TJ'),
('Tansania', 'TZ'),
('Thailand', 'TH'),
('Togo', 'TG'),
('Tonga', 'TO'),
('Trinidad und Tobago', 'TT'),
('Tschad', 'TD'),
('Tschechien', 'CZ'),
('Tunesien', 'TN'),
('Türkei', 'TR'),
('Turkmenistan', 'TM'),
('Tuvalu', 'TV'),
('Uganda', 'UG'),
('Ukraine', 'UA'),
('Ungarn', 'HU'),
('Uruguay', 'UY'),
('Usbekistan', 'UZ'),
('Vanuatu', 'VU'),
('Vatikanstadt', 'VA'),
('Venezuela', 'VE'),
('Vereinigte Arabische Emirate', 'AE'),
('Vereinigte Staaten', 'US'),
('Vereinigtes Königreich', 'GB'),
('Vietnam', 'VN'),
('Weißrussland', 'BY'),
('Zentralafrikanische Republik', 'CF'),
('Zypern', 'CY');
